// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa3IuOs9xIrDL5s4iu0OX-00GFhisg-Yw',
    appId: '1:28152228755:web:4b458ac1b7d083343d1666',
    messagingSenderId: '28152228755',
    projectId: 'fir-project1-e2f88',
    authDomain: 'fir-project1-e2f88.firebaseapp.com',
    storageBucket: 'fir-project1-e2f88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLEq7WfAdsXB9y93JyM-kF3EBw1CW2C9A',
    appId: '1:28152228755:android:52e7907c64b4af2a3d1666',
    messagingSenderId: '28152228755',
    projectId: 'fir-project1-e2f88',
    storageBucket: 'fir-project1-e2f88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEdXXYwP1ppjSDNtjnVqLKlwLbQams-_E',
    appId: '1:28152228755:ios:879130653a888b343d1666',
    messagingSenderId: '28152228755',
    projectId: 'fir-project1-e2f88',
    storageBucket: 'fir-project1-e2f88.appspot.com',
    iosBundleId: 'com.example.boltClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEdXXYwP1ppjSDNtjnVqLKlwLbQams-_E',
    appId: '1:28152228755:ios:3009d8ba58f30d243d1666',
    messagingSenderId: '28152228755',
    projectId: 'fir-project1-e2f88',
    storageBucket: 'fir-project1-e2f88.appspot.com',
    iosBundleId: 'com.example.boltClone.RunnerTests',
  );
}
